export const WORLD_CITIES = [
  { name:"Вена, Австрия",            flag:"🇦🇹", score:98, icon:"🎵", tagline:"Столица музыки и кофе",          strategy:"culture" },
  { name:"Цюрих, Швейцария",         flag:"🇨🇭", score:97, icon:"⛰️", tagline:"Альпы, банки, шоколад",          strategy:"economy" },
  { name:"Копенгаген, Дания",        flag:"🇩🇰", score:96, icon:"🚲", tagline:"Город велосипедов и хюгге",      strategy:"ecology" },
  { name:"Мельбурн, Австралия",      flag:"🇦🇺", score:95, icon:"☕", tagline:"Кофейная столица мира",           strategy:"balanced" },
  { name:"Ванкувер, Канада",         flag:"🇨🇦", score:95, icon:"🌲", tagline:"Горы встречают океан",            strategy:"ecology" },
  { name:"Хельсинки, Финляндия",     flag:"🇫🇮", score:94, icon:"🧖", tagline:"Сауны и дизайн",                  strategy:"digital" },
  { name:"Рейкьявик, Исландия",      flag:"🇮🇸", score:94, icon:"🌋", tagline:"Гейзеры и северное сияние",       strategy:"ecology" },
  { name:"Осло, Норвегия",           flag:"🇳🇴", score:93, icon:"🛥️", tagline:"Фьорды и благополучие",           strategy:"ecology" },
  { name:"Токио, Япония",            flag:"🇯🇵", score:93, icon:"🗼", tagline:"Порядок, технологии, рамен",       strategy:"digital" },
  { name:"Амстердам, Нидерланды",    flag:"🇳🇱", score:92, icon:"🌷", tagline:"Каналы и свобода",                strategy:"balanced" },
  { name:"Мюнхен, Германия",         flag:"🇩🇪", score:92, icon:"🍺", tagline:"Баварская столица",               strategy:"economy" },
  { name:"Люксембург",               flag:"🇱🇺", score:91, icon:"🏦", tagline:"Маленький, но богатый",            strategy:"economy" },
  { name:"Сингапур",                 flag:"🇸🇬", score:91, icon:"🏙️", tagline:"Город-сад будущего",              strategy:"digital" },
  { name:"Барселона, Испания",       flag:"🇪🇸", score:90, icon:"🎨", tagline:"Гауди, пляжи, тапас",             strategy:"culture" },
  { name:"Окленд, Новая Зеландия",   flag:"🇳🇿", score:90, icon:"⛵", tagline:"Город парусов",                   strategy:"ecology" },
  { name:"Стокгольм, Швеция",        flag:"🇸🇪", score:89, icon:"🏔️", tagline:"14 островов и инновации",         strategy:"digital" },
  { name:"Берлин, Германия",         flag:"🇩🇪", score:88, icon:"🎶", tagline:"Культура и стартапы",             strategy:"culture" },
  { name:"Дублин, Ирландия",         flag:"🇮🇪", score:87, icon:"🍀", tagline:"Пабы, литература, IT",            strategy:"digital" },
  { name:"Монреаль, Канада",         flag:"🇨🇦", score:87, icon:"🎭", tagline:"Французский шарм",               strategy:"culture" },
  { name:"Лиссабон, Португалия",     flag:"🇵🇹", score:86, icon:"🌊", tagline:"Мягкий климат и азулежу",         strategy:"culture" },
  { name:"Сеул, Южная Корея",        flag:"🇰🇷", score:86, icon:"📱", tagline:"K-pop и технологии",              strategy:"digital" },
  { name:"Брюссель, Бельгия",        flag:"🇧🇪", score:85, icon:"🧇", tagline:"Вафли и евробюрократия",          strategy:"balanced" },
  { name:"Прага, Чехия",             flag:"🇨🇿", score:85, icon:"🏰", tagline:"Средневековье и пиво",            strategy:"culture" },
  { name:"Мадрид, Испания",          flag:"🇪🇸", score:84, icon:"☀️", tagline:"Жизнь на площади",               strategy:"culture" },
  { name:"Тайбэй, Тайвань",          flag:"🇹🇼", score:84, icon:"🏮", tagline:"Ночные рынки и хайтек",           strategy:"digital" },
  { name:"Абу-Даби, ОАЭ",            flag:"🇦🇪", score:84, icon:"🕌", tagline:"Культура и нефть",               strategy:"infrastructure" },
  { name:"Таллин, Эстония",          flag:"🇪🇪", score:83, icon:"💻", tagline:"Цифровое государство",            strategy:"digital" },
  { name:"Рим, Италия",              flag:"🇮🇹", score:83, icon:"🏟️", tagline:"Вечный город",                   strategy:"culture" },
  { name:"Дубай, ОАЭ",               flag:"🇦🇪", score:82, icon:"🏗️", tagline:"Небоскрёбы в пустыне",            strategy:"infrastructure" },
  { name:"Куала-Лумпур, Малайзия",   flag:"🇲🇾", score:82, icon:"🏗️", tagline:"Башни-близнецы",                  strategy:"economy" },
  { name:"Монтевидео, Уругвай",      flag:"🇺🇾", score:81, icon:"🧉", tagline:"Мате и спокойствие",             strategy:"balanced" },
  { name:"Порту, Португалия",        flag:"🇵🇹", score:81, icon:"🍷", tagline:"Портвейн и азулежу",              strategy:"culture" },
  { name:"Варшава, Польша",          flag:"🇵🇱", score:80, icon:"🏛️", tagline:"Возрождённый из пепла",           strategy:"infrastructure" },
  { name:"Любляна, Словения",        flag:"🇸🇮", score:80, icon:"🐉", tagline:"Зелёная столица Европы",          strategy:"ecology" },
  { name:"Доха, Катар",              flag:"🇶🇦", score:79, icon:"🏟️", tagline:"Пустыня и амбиции",               strategy:"infrastructure" },
  { name:"Будапешт, Венгрия",        flag:"🇭🇺", score:79, icon:"♨️", tagline:"Термальные купальни",             strategy:"culture" },
  { name:"Росток, Германия",         flag:"🇩🇪", score:78, icon:"⚓", tagline:"Балтийские ворота",               strategy:"infrastructure" },
  { name:"Буэнос-Айрес, Аргентина",  flag:"🇦🇷", score:78, icon:"💃", tagline:"Танго и стейки",                  strategy:"culture" },
  { name:"Маскат, Оман",             flag:"🇴🇲", score:78, icon:"🕌", tagline:"Тихая роскошь Аравии",            strategy:"balanced" },
  { name:"Загреб, Хорватия",         flag:"🇭🇷", score:77, icon:"🏘️", tagline:"Барочный уют Балкан",             strategy:"culture" },
  { name:"Рига, Латвия",             flag:"🇱🇻", score:76, icon:"🏰", tagline:"Югендстиль и шпроты",             strategy:"culture" },
  { name:"Братислава, Словакия",     flag:"🇸🇰", score:76, icon:"🏰", tagline:"Маленькая столица",               strategy:"balanced" },
  { name:"Вильнюс, Литва",           flag:"🇱🇹", score:75, icon:"🏛️", tagline:"Барочная жемчужина Балтии",       strategy:"culture" },
  { name:"Мехико, Мексика",          flag:"🇲🇽", score:75, icon:"🌮", tagline:"Хаос и культура",                 strategy:"economy" },
  { name:"Тбилиси, Грузия",          flag:"🇬🇪", score:74, icon:"🍷", tagline:"Вино и гостеприимство",           strategy:"culture" },
  { name:"Москва, Россия",           flag:"🇷🇺", score:74, icon:"🏛️", tagline:"Столица, которая никогда не спит", strategy:"infrastructure" },
  { name:"Бухарест, Румыния",        flag:"🇷🇴", score:73, icon:"🏛️", tagline:"Маленький Париж Востока",         strategy:"culture" },
  { name:"Сантьяго, Чили",           flag:"🇨🇱", score:73, icon:"🏔️", tagline:"Анды за окном",                  strategy:"balanced" },
  { name:"Афины, Греция",            flag:"🇬🇷", score:72, icon:"🏛️", tagline:"Колыбель демократии",             strategy:"culture" },
  { name:"Белград, Сербия",          flag:"🇷🇸", score:72, icon:"🎺", tagline:"Ночная жизнь у двух рек",          strategy:"culture" },
  { name:"Санкт-Петербург, Россия",  flag:"🇷🇺", score:71, icon:"🏛️", tagline:"Культурная столица",              strategy:"culture" },
  { name:"Эр-Рияд, Саудовская Аравия",flag:"🇸🇦",score:71, icon:"🏙️", tagline:"NEOM и будущее",                  strategy:"infrastructure" },
  { name:"Ереван, Армения",          flag:"🇦🇲", score:70, icon:"🏔️", tagline:"Розовый город у Арарата",          strategy:"balanced" },
  { name:"Медельин, Колумбия",       flag:"🇨🇴", score:69, icon:"🌺", tagline:"Город вечной весны",               strategy:"infrastructure" },
  { name:"Казань, Россия",           flag:"🇷🇺", score:68, icon:"🕌", tagline:"Третья столица России",            strategy:"culture" },
  { name:"Бангкок, Таиланд",         flag:"🇹🇭", score:67, icon:"🛕", tagline:"Уличная еда и хаос",              strategy:"economy" },
  { name:"Астана, Казахстан",        flag:"🇰🇿", score:66, icon:"🏙️", tagline:"Футуристическая столица степи",   strategy:"infrastructure" },
  { name:"Лима, Перу",               flag:"🇵🇪", score:66, icon:"🏛️", tagline:"Гастрономическая столица",        strategy:"economy" },
  { name:"Екатеринбург, Россия",     flag:"🇷🇺", score:65, icon:"🏭", tagline:"Столица Урала",                   strategy:"economy" },
  { name:"Нижний Новгород, Россия",  flag:"🇷🇺", score:64, icon:"⛪", tagline:"Слияние Оки и Волги",             strategy:"balanced" },
  { name:"Богота, Колумбия",         flag:"🇨🇴", score:64, icon:"🌿", tagline:"2600 метров над морем",            strategy:"ecology" },
  { name:"Стамбул, Турция",          flag:"🇹🇷", score:63, icon:"🕌", tagline:"Мост между мирами",               strategy:"economy" },
  { name:"Баку, Азербайджан",        flag:"🇦🇿", score:63, icon:"🔥", tagline:"Город ветров и огня",             strategy:"economy" },
  { name:"Кейптаун, ЮАР",            flag:"🇿🇦", score:62, icon:"🏔️", tagline:"Столовая гора и океан",           strategy:"balanced" },
  { name:"Сараево, Босния",          flag:"🇧🇦", score:62, icon:"🌉", tagline:"Восток встречает Запад",           strategy:"culture" },
  { name:"Краснодар, Россия",        flag:"🇷🇺", score:61, icon:"🌻", tagline:"Южная столица",                   strategy:"economy" },
  { name:"Минск, Беларусь",          flag:"🇧🇾", score:61, icon:"🏛️", tagline:"Город-герой",                    strategy:"infrastructure" },
  { name:"Тюмень, Россия",           flag:"🇷🇺", score:60, icon:"🛢️", tagline:"Нефтяная столица Сибири",          strategy:"economy" },
  { name:"Киев, Украина",            flag:"🇺🇦", score:60, icon:"🌻", tagline:"Золотые купола и каштаны",         strategy:"culture" },
  { name:"Тирана, Албания",          flag:"🇦🇱", score:59, icon:"🏛️", tagline:"Цветные фасады Балкан",           strategy:"balanced" },
  { name:"Хошимин, Вьетнам",         flag:"🇻🇳", score:58, icon:"🛵", tagline:"Энергия Юго-Востока",             strategy:"economy" },
  { name:"Калуга, Россия",           flag:"🇷🇺", score:58, icon:"🚀", tagline:"Колыбель космонавтики",            strategy:"digital" },
  { name:"Новосибирск, Россия",      flag:"🇷🇺", score:57, icon:"🔬", tagline:"Академгородок",                   strategy:"digital" },
  { name:"Ростов-на-Дону, Россия",   flag:"🇷🇺", score:56, icon:"🌻", tagline:"Ворота Кавказа",                  strategy:"economy" },
  { name:"Касабланка, Марокко",      flag:"🇲🇦", score:57, icon:"🕌", tagline:"Белый город на Атлантике",         strategy:"economy" },
  { name:"Ханой, Вьетнам",           flag:"🇻🇳", score:56, icon:"🏍️", tagline:"Миллион мотобайков",              strategy:"economy" },
  { name:"Каир, Египет",             flag:"🇪🇬", score:55, icon:"🔺", tagline:"У подножья пирамид",               strategy:"culture" },
  { name:"Самара, Россия",           flag:"🇷🇺", score:54, icon:"🚀", tagline:"Космический город",               strategy:"digital" },
  { name:"Владивосток, Россия",      flag:"🇷🇺", score:54, icon:"🌊", tagline:"Там, где начинается Россия",       strategy:"infrastructure" },
  { name:"Пуна, Индия",              flag:"🇮🇳", score:53, icon:"💻", tagline:"IT-столица Индии",                strategy:"digital" },
  { name:"Воронеж, Россия",          flag:"🇷🇺", score:52, icon:"⚓", tagline:"Колыбель русского флота",           strategy:"balanced" },
  { name:"Ташкент, Узбекистан",      flag:"🇺🇿", score:52, icon:"🕌", tagline:"Восточный базар и плов",           strategy:"balanced" },
  { name:"Уфа, Россия",              flag:"🇷🇺", score:51, icon:"🏔️", tagline:"Три реки, три культуры",           strategy:"ecology" },
  { name:"Якарта, Индонезия",        flag:"🇮🇩", score:50, icon:"🏙️", tagline:"Тонущий мегаполис",               strategy:"economy" },
  { name:"Пермь, Россия",            flag:"🇷🇺", score:49, icon:"🎭", tagline:"Край настоящих людей",             strategy:"culture" },
  { name:"Манила, Филиппины",        flag:"🇵🇭", score:48, icon:"🏝️", tagline:"Хаотичный рай",                   strategy:"economy" },
  { name:"Кигали, Руанда",           flag:"🇷🇼", score:47, icon:"🏔️", tagline:"Чистейший город Африки",          strategy:"ecology" },
  { name:"Саратов, Россия",          flag:"🇷🇺", score:46, icon:"🌾", tagline:"Волжская провинция",               strategy:"balanced" },
  { name:"Аккра, Гана",              flag:"🇬🇭", score:46, icon:"🏖️", tagline:"Ворота Западной Африки",           strategy:"economy" },
  { name:"Найроби, Кения",           flag:"🇰🇪", score:44, icon:"🦁", tagline:"Сафари и контрасты",               strategy:"economy" },
  { name:"Пномпень, Камбоджа",       flag:"🇰🇭", score:43, icon:"🏛️", tagline:"Кхмерское возрождение",           strategy:"culture" },
  { name:"Аддис-Абеба, Эфиопия",     flag:"🇪🇹", score:42, icon:"☕", tagline:"Родина кофе",                     strategy:"balanced" },
  { name:"Дар-эс-Салам, Танзания",   flag:"🇹🇿", score:41, icon:"🌅", tagline:"Гавань мира",                     strategy:"infrastructure" },
  { name:"Алматы, Казахстан",        flag:"🇰🇿", score:37, icon:"🍎", tagline:"Город яблок",                     strategy:"balanced" },
  { name:"Карачи, Пакистан",         flag:"🇵🇰", score:40, icon:"🏭", tagline:"Порт и промышленность",            strategy:"economy" },
  { name:"Лагос, Нигерия",           flag:"🇳🇬", score:38, icon:"🎵", tagline:"Афробит и 20 миллионов",           strategy:"economy" },
  { name:"Омск, Россия",             flag:"🇷🇺", score:36, icon:"🏭", tagline:"Не пытайся уехать",                strategy:"economy" },
  { name:"Тунис, Тунис",             flag:"🇹🇳", score:55, icon:"🏛️", tagline:"Карфаген и жасмин",               strategy:"culture" },
  { name:"Дакка, Бангладеш",         flag:"🇧🇩", score:32, icon:"🧵", tagline:"Мировая швейная фабрика",          strategy:"economy" },
  { name:"Кабул, Афганистан",        flag:"🇦🇫", score:22, icon:"🏔️", tagline:"Город, который не сдаётся",        strategy:"balanced" },
];
