export const ALL_DECISIONS = [
  // Infrastructure
  { id:"road_repair", name:"Ремонт дорог", desc:"Капитальный ремонт дорожного покрытия.", cost:140, effects:{infrastructure:10,safety:2,economy:1,ecology:-2}, cat:"infrastructure" },
  { id:"storm_drain", name:"Ливневая канализация", desc:"Система отвода дождевой воды.", cost:160, effects:{infrastructure:8,safety:4,ecology:2}, once:true, cat:"infrastructure" },
  { id:"shuttle", name:"Шаттл до ж/д станции", desc:"Регулярный автобус-шаттл к станции.", cost:55, effects:{infrastructure:5,economy:2,ecology:-1}, cat:"infrastructure" },
  { id:"housing", name:"Программа доступного жилья", desc:"Жилой комплекс для молодых семей.", cost:200, effects:{economy:4,infrastructure:3,ecology:-3}, populationEffect:200, cat:"infrastructure" },
  { id:"waterworks", name:"Реконструкция водопровода", desc:"Замена изношенных труб и насосов.", cost:170, effects:{infrastructure:9,healthcare:2}, once:true, cat:"infrastructure" },
  // Digital
  { id:"fiber", name:"Оптоволокно во все районы", desc:"Высокоскоростной интернет.", cost:160, effects:{digital:10,economy:2,infrastructure:1}, once:true, cat:"digital", unlocks:["smart_city"] },
  { id:"smart_city", name:"Платформа «Умный Звенигород»", desc:"Единая цифровая платформа городских сервисов.", cost:130, effects:{digital:8,infrastructure:2,safety:2}, once:true, requires:{digital:30}, cat:"digital", unlocks:["ai_city"] },
  { id:"wifi", name:"Wi-Fi в общественных местах", desc:"Бесплатный Wi-Fi в парках и на остановках.", cost:50, effects:{digital:4,culture:1}, cat:"digital" },
  { id:"digital_library", name:"Цифровая библиотека", desc:"Онлайн-каталог и электронные читальные залы.", cost:55, effects:{education:5,digital:3,culture:2}, cat:"digital" },
  { id:"ai_city", name:"AI-система управления", desc:"Искусственный интеллект оптимизирует городские процессы.", cost:160, effects:{digital:6,safety:3,economy:2}, once:true, requires:{digital:60}, cat:"digital" },
  // Ecology
  { id:"park_river", name:"Парк у Москвы-реки", desc:"Реконструкция набережной с велодорожками.", cost:120, effects:{ecology:6,culture:3,safety:1}, cat:"ecology" },
  { id:"recycling", name:"Раздельный сбор мусора", desc:"Контейнеры и программа переработки.", cost:70, effects:{ecology:7,culture:1}, cat:"ecology" },
  { id:"greening", name:"Озеленение улиц", desc:"Высадка деревьев на центральных улицах.", cost:45, effects:{ecology:5,culture:1}, cat:"ecology" },
  { id:"solar", name:"Солнечные панели", desc:"Панели на муниципальных зданиях.", cost:130, effects:{ecology:5,economy:2,digital:1}, cat:"ecology" },
  { id:"water_treatment", name:"Очистные сооружения", desc:"Современные очистные для сточных вод.", cost:180, effects:{ecology:10,healthcare:2}, once:true, cat:"ecology" },
  { id:"eco_route", name:"Эко-маршрут «Москва-река»", desc:"Пешеходно-велосипедный маршрут вдоль реки.", cost:90, effects:{ecology:5,culture:4}, once:true, requires:{ecology:50}, cat:"ecology" },
  // Culture
  { id:"festival", name:"«Звенигородские вечера»", desc:"Фестиваль музыки и искусства.", cost:45, effects:{culture:6,economy:2,safety:-2}, cat:"culture" },
  { id:"monastery", name:"Реставрация монастыря", desc:"Восстановление Саввино-Сторожевского монастыря.", cost:120, effects:{culture:10,economy:3}, once:true, cat:"culture", unlocks:["tourism_cluster"] },
  { id:"branding", name:"Бренд «Город у реки»", desc:"Туристический бренд и маркетинговая кампания.", cost:65, effects:{culture:4,economy:4}, once:true, cat:"culture" },
  { id:"farmer_market", name:"Фермерский рынок", desc:"Еженедельный рынок на центральной площади.", cost:30, effects:{economy:3,culture:3,ecology:1}, cat:"culture" },
  { id:"art_residence", name:"Арт-резиденция", desc:"Творческое пространство для художников.", cost:75, effects:{culture:5,education:1}, cat:"culture" },
  { id:"tourism_cluster", name:"Туристический кластер", desc:"Комплексное развитие туризма у монастыря.", cost:200, effects:{culture:8,economy:6,infrastructure:-2}, once:true, requires:{culture:55}, cat:"culture" },
  // Healthcare
  { id:"clinic_upgrade", name:"Модернизация поликлиники", desc:"Новое оборудование и ремонт.", cost:200, effects:{healthcare:12,safety:1}, once:true, cat:"healthcare", unlocks:["telemedicine"] },
  { id:"senior_center", name:"Центр активного долголетия", desc:"Центр для пожилых жителей.", cost:100, effects:{healthcare:5,culture:3,safety:1}, cat:"healthcare" },
  { id:"ambulance", name:"Новые машины скорой", desc:"Обновление парка скорой помощи.", cost:90, effects:{healthcare:6,safety:2}, cat:"healthcare" },
  { id:"prevention", name:"Программа профилактики", desc:"Бесплатные медосмотры и вакцинация.", cost:55, effects:{healthcare:4,education:1}, cat:"healthcare" },
  { id:"telemedicine", name:"Телемедицина", desc:"Дистанционные консультации врачей.", cost:100, effects:{healthcare:6,digital:3}, once:true, requires:{healthcare:45}, cat:"healthcare" },
  // Education
  { id:"school_repair", name:"Ремонт школ", desc:"Капитальный ремонт и оборудование.", cost:130, effects:{education:8,safety:2}, cat:"education", unlocks:["stem_lab"] },
  { id:"kindergarten", name:"Новый детский сад", desc:"Детский сад на 120 мест.", cost:170, effects:{education:6,safety:1}, once:true, populationEffect:150, cat:"education" },
  { id:"it_classes", name:"IT-классы в школах", desc:"Робототехника и программирование.", cost:75, effects:{education:5,digital:3}, cat:"education" },
  { id:"scholarships", name:"Стипендии для студентов", desc:"Муниципальные стипендии.", cost:45, effects:{education:4,culture:1}, cat:"education" },
  { id:"stem_lab", name:"IT-академия для подростков", desc:"Продвинутый центр IT-образования.", cost:130, effects:{education:6,digital:4}, once:true, requires:{education:50}, cat:"education" },
  // Safety
  { id:"cameras", name:"Умные камеры", desc:"Видеонаблюдение с аналитикой.", cost:90, effects:{safety:8,digital:2}, cat:"safety" },
  { id:"fire_station", name:"Модернизация пожарной части", desc:"Новая техника и расширение депо.", cost:90, effects:{safety:7,infrastructure:1}, once:true, cat:"safety" },
  { id:"street_lights", name:"Уличное освещение", desc:"LED-фонари на тёмных улицах.", cost:65, effects:{safety:5,infrastructure:1}, cat:"safety" },
  { id:"patrol", name:"Народная дружина", desc:"Добровольные дружины.", cost:25, effects:{safety:3,culture:1}, cat:"safety" },
  // Economy
  { id:"it_tax_breaks", name:"Налоговые льготы для IT", desc:"Налоговые каникулы для IT-компаний.", cost:50, effects:{economy:6,digital:3}, recurringIncome:{base:0,maintenance:40,decayPerTurn:0}, once:true, cat:"economy", unlocks:["technopark"] },
  { id:"small_biz_grants", name:"Гранты малому бизнесу", desc:"Программа грантов.", cost:75, effects:{economy:7,digital:1}, cat:"economy" },
  { id:"coworking", name:"Муниципальный коворкинг", desc:"Рабочее пространство для фрилансеров.", cost:75, effects:{digital:4,economy:4,culture:2}, cat:"economy" },
  { id:"logistics_hub", name:"Логистический хаб", desc:"Транспортно-логистический центр.", cost:150, effects:{economy:8,infrastructure:3,ecology:-2}, once:true, cat:"economy" },
  { id:"technopark", name:"Технопарк «Звенигород-Тех»", desc:"Технологический парк для IT и стартапов.", cost:250, effects:{economy:10,digital:6}, once:true, requires:{economy:50,digital:45}, cat:"economy" },
  // Trade-offs
  { id:"factory", name:"Завод на окраине", desc:"Рабочие места ценой экологии.", cost:100, effects:{economy:10,ecology:-10}, populationEffect:300, recurringIncome:{base:50,maintenance:20,decayPerTurn:2}, once:true, cat:"tradeoff" },
  { id:"luxury_housing", name:"Элитный ЖК", desc:"Доход для бюджета, нагрузка на инфраструктуру.", cost:80, effects:{economy:6,ecology:-5,infrastructure:-4}, cat:"tradeoff" },
  { id:"parking_lots", name:"Вырубка леса под парковки", desc:"Больше парковок за счёт зелёных зон.", cost:50, effects:{infrastructure:6,ecology:-12}, cat:"tradeoff" },
  { id:"casino_zone", name:"Казино-зона", desc:"Огромный доход, но удар по культуре.", cost:130, effects:{economy:12,culture:-7,safety:-8}, recurringIncome:{base:60,maintenance:25,decayPerTurn:3}, once:true, cat:"tradeoff" },
  { id:"paid_parking", name:"Платные парковки в центре", desc:"Плата за парковку в историческом центре.", cost:25, effects:{economy:3,culture:-4}, recurringIncome:{base:20,maintenance:8,decayPerTurn:1}, once:true, cat:"tradeoff" },
  // New decisions v3.5
  { id:"bike_sharing", name:"Велопрокат", desc:"Система городского велопроката.", cost:60, effects:{ecology:4,infrastructure:2,culture:2}, cat:"ecology" },
  { id:"food_delivery", name:"Партнёрство с доставкой", desc:"Городская программа поддержки локальной доставки.", cost:35, effects:{economy:4,digital:2}, cat:"economy" },
  { id:"senior_bus", name:"Бесплатный автобус для пожилых", desc:"Бесплатный маршрут для пенсионеров.", cost:40, effects:{healthcare:3,safety:2,infrastructure:1}, cat:"healthcare" },
  { id:"youth_center", name:"Молодёжный центр", desc:"Площадка для кружков и мероприятий.", cost:80, effects:{education:4,culture:4,safety:2}, cat:"education" },
  { id:"night_lighting", name:"Архитектурная подсветка", desc:"Подсветка исторических зданий.", cost:45, effects:{culture:4,safety:3,economy:1}, cat:"culture" },
  { id:"electric_buses", name:"Электрические автобусы", desc:"Замена дизельных автобусов.", cost:180, effects:{ecology:6,infrastructure:4,digital:2}, once:true, cat:"ecology" },
  { id:"sport_complex", name:"Спорткомплекс", desc:"Физкультурно-оздоровительный комплекс.", cost:200, effects:{healthcare:6,education:3,culture:3,safety:1}, once:true, cat:"healthcare" },
  { id:"river_cleanup", name:"Очистка Москвы-реки", desc:"Экологическая очистка реки.", cost:90, effects:{ecology:8,healthcare:2,culture:1}, cat:"ecology" },
  { id:"startup_incubator", name:"Бизнес-инкубатор", desc:"Инкубатор для стартапов при технопарке.", cost:100, effects:{economy:6,digital:4,education:2}, requires:{economy:40}, cat:"economy" },
  { id:"heritage_restoration", name:"Реставрация усадеб", desc:"Восстановление усадеб и памятников.", cost:150, effects:{culture:8,economy:3,education:1}, cat:"culture" },
  { id:"emergency_center", name:"Центр МЧС", desc:"Новый пост МЧС с современным оснащением.", cost:120, effects:{safety:8,infrastructure:2}, once:true, cat:"safety" },
  { id:"composting", name:"Программа компостирования", desc:"Городская программа компостирования.", cost:30, effects:{ecology:4,education:1}, cat:"ecology" },
  { id:"drone_delivery", name:"Дроны-курьеры", desc:"Пилотный проект доставки дронами.", cost:80, effects:{digital:5,economy:3,safety:-1}, requires:{digital:50}, cat:"digital" },
  { id:"public_garden", name:"Общественный огород", desc:"Городские грядки для жителей.", cost:20, effects:{ecology:3,culture:2,healthcare:1}, cat:"ecology" },
  { id:"music_school", name:"Музыкальная школа", desc:"Бесплатная музыкальная школа.", cost:70, effects:{culture:5,education:4}, cat:"culture" },
];
